# Generated by Django 3.1 on 2020-09-03 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil Resmi')),
                ('mobilePhone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Telefon Numarası')),
                ('gender', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtmek İstemiyorum', 'Belirtmek İstemiyorum')], default='Erkek', max_length=128, verbose_name='Cinsiyeti')),
                ('birthDate', models.DateField(null=True, verbose_name='Doğum Tarihi')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Doğum Yılı')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('notification', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
