# Generated by Django 3.1 on 2020-10-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0003_auto_20201001_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='chassisNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='currentKM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engineNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
