# Generated by Django 3.1 on 2020-10-08 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0004_auto_20201008_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='modificationDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
    ]
