# Generated by Django 3.1.1 on 2020-10-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0006_car_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='barcode_number',
            new_name='barcodeNumber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='isOpen',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='netPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Ürün Resmi'),
        ),
        migrations.AddField(
            model_name='product',
            name='taxRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='totalProduct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
