# Generated by Django 3.1.1 on 2020-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0008_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
