# Generated by Django 3.1.1 on 2020-11-28 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0009_auto_20201127_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmName', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='total_price',
            new_name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_order',
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='modificationDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceKM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.profile'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='productTotalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
