# Generated by Django 3.1.1 on 2020-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0012_auto_20201212_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='netPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='taxRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='totalProduct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
