# Generated by Django 3.1.1 on 2020-12-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0015_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
