# Generated by Django 3.1.1 on 2020-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0017_auto_20201227_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='taxOffice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
