# Generated by Django 3.1.1 on 2021-01-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0019_auto_20210103_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='laborName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
