# Generated by Django 3.1.1 on 2021-01-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0020_service_laborname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('remainingDebt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paymentSituation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.paymentsituation')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='laborPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PaymentMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('checkingAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.checkingaccount')),
                ('paymentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.paymenttype')),
            ],
        ),
        migrations.AddField(
            model_name='checkingaccount',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.service'),
        ),
    ]
