# Generated by Django 3.1 on 2021-01-07 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0021_auto_20210103_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='paymentmovement',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
