# Generated by Django 3.1 on 2021-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0024_auto_20210111_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='receiverPerson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
