# Generated by Django 3.1.1 on 2021-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0026_auto_20210207_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
