# Generated by Django 3.1.7 on 2021-03-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0031_address_telephone'),
        ('carService', '0029_profile_issendmail'),
    ]

    operations = [
    ]
