# Generated by Django 3.1 on 2021-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0032_merge_20210315_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogsModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api', models.CharField(help_text='API URL', max_length=512)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('client_ip_address', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, help_text='Response status code')),
                ('execution_time', models.DecimalField(decimal_places=5, help_text='Server execution time (Not complete response time.)', max_digits=8)),
                ('added_on', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
