# Generated by Django 3.1.7 on 2021-05-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0033_auto_20210331_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='service',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='isCameraOpen',
        ),
        migrations.RemoveField(
            model_name='service',
            name='laborName',
        ),
        migrations.RemoveField(
            model_name='service',
            name='laborPrice',
        ),
        migrations.RemoveField(
            model_name='service',
            name='laborTaxRate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='receiverPerson',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceman',
        ),
        migrations.RemoveField(
            model_name='service',
            name='totalPrice',
        ),
    ]
